### ISSUE TITLE
when connections is very large,it can be very slow

### ISSUE THREAD

**Issue by gqdw** [mutz0623/zabbix_TCP-state-count-module#1]
resolve /proc/net/tcp will very slow .

**Comment by mutz0623** [comment]
How many lines and how long will it take?

**Comment by gqdw** [comment]
hi,mutz0623 ,about 2w line in /proc/net/tcp  , for about 3s ~4seconds ,use lots of CPU system time
![tcpcount](https://cloud.githubusercontent.com/assets/3916050/26766916/ae7ad674-49cc-11e7-8e8a-ef3da417482a.PNG)

**Comment by gqdw** [comment]
2w = 20,000

**Comment by mutz0623** [comment]
Improved for read from /proc/net/tcp.
Then, I think that terrible system time will be little better than before.

And if still probrems not solved, check the following this
- Increase number of agent listener processes
  "StartAgents" parameter in zabbix_agentd.conf
  que of zabbix server would be increasing? then number of processes may be insufficient.
- too many items to agent's listener process or resources
 reduce items (disable unused port watching) or extend intervals

**Comment by mutz0623** [comment]
![1](https://user-images.githubusercontent.com/6974918/29742776-09abf30a-8ac0-11e7-8046-5714cf3e6f49.png)

Improved the performance.
And decreased possibility for become slow items.

- a is commit  1a43c0c5aca52183fa60e496f5553005969294ec
    - before improve
- b is commit de74884ddf60aeb9e0baf40228cc87ec4cd9ac02
    - improved but using /proc/net/tcp
- c is commit bfefc0129b8c8c74b9bd40fb8341a0a3843b2d5c
    - improved using netlink

----
(added 2017-08-30)

The graph above shows, in case of changed item's interval time to 5 sec from 60 sec with example template.
( 2CPU,4GB memory, CentOS7, work both zabbix server and agent in one machine)
