### ISSUE TITLE
cannot load module "tcp_count.so": /etc/zabbix/modules/tcp_count.so: undefined symbol: program_type

### ISSUE THREAD

**Issue by n2k3b1** [mutz0623/zabbix_TCP-state-count-module#2]
Hi,
I can not start zabbix-agent after doing as your document. I got an issue as following:

```
18024:20190419:035032.104 using configuration file: /etc/zabbix/zabbix_agentd.conf
18024:20190419:035032.105 cannot load module "tcp_count.so": /etc/zabbix/modules/tcp_count.so: undefined symbol: program_type
18024:20190419:035032.105 loading modules failed, exiting...
```

Please advice.

**Comment by n2k3b1** [comment]
Hi,
I can not start zabbix-agent after doing as your document. I got an issue as following:

> 18024:20190419:035032.104 using configuration file: /etc/zabbix/zabbix_agentd.conf
>  18024:20190419:035032.105 cannot load module "tcp_count.so": /etc/zabbix/modules/tcp_count.so: undefined symbol: program_type
>  18024:20190419:035032.105 loading modules failed, exiting...

Please advice.

**Comment by mutz0623** [comment]
Thanks for comment.
Please check your Zabbix agent version.

This module will supports 3.0 or later.

regards.

**Comment by mutz0623** [comment]
Removed the cause of compatibility issues.
Please check for compile with same version Zabbix sources as your Zabbix environment.

regards.

**Comment by n2k3b1** [comment]
Thanks you.
